#!/bin/bash

# Kasutajalt küsitakse kujundi ridade arv ja trükitakse kahanev tärnide kujund.

# Kasutajalt ridade arvu küsimine
read -p "Sisesta ridade arv: " ridade_arv

# Kujundi trükkimine
for ((i=ridade_arv; i>0; i--))
do
    for ((j=1; j<=i; j++))
    do
        echo -n "* "
    done
    echo
done
