#!/bin/bash

# Pakkuda kasutajale valik erinevate toitude vahel ja vastavalt valikule kuvada vastav sõnum.

# Menüü
echo "Menüü:"
echo "1) Liha ja kartulid"
echo "2) Kala ja krõpsud"
echo "3) Supp ja salat"

# Kasutajale valiku pakkumine
read -p "Tee oma valik (1 või 2 või 3): " valik

# Valiku põhjal vastava sõnumi kuvamine
case $valik in
    1)
        echo "Väga maitsev, aga jälgi oma tervist!"
        echo "Head isu!"
        ;;
    2)
        echo "Brititoit on maitsev!"
        echo "Head isu!"
        ;;
    3)
        echo "Nii tervislik ja igav..."
        echo "Head isu!"
        ;;
    *)
        echo "Vale valik, palun proovi uuesti."
        ;;
esac

